### ISSUE TITLE
Performance issue in scripts/make_tfrecord.py

### ISSUE THREAD

**Issue by DLPerf** [cosmoquester/transformers-bart-pretrain#18]
Hello! Our static bug checker has found a performance issue in scripts/make_tfrecord.py:  [`read_data`](https://github.com/cosmoquester/transformers-bart-pretrain/blob/b3718ce9c68ae0e636ca95e075772cdd9ee853de/scripts/make_tfrecord.py#L60) is repeatedly called in a for loop, but there is a tf.function decorated function [`tokenize_fn`](https://github.com/cosmoquester/transformers-bart-pretrain/blob/b3718ce9c68ae0e636ca95e075772cdd9ee853de/scripts/make_tfrecord.py#L21) defined and called in  [`read_data`](https://github.com/cosmoquester/transformers-bart-pretrain/blob/b3718ce9c68ae0e636ca95e075772cdd9ee853de/scripts/make_tfrecord.py#L19). 

In that case, when `read_data` is called in a loop, the function `tokenize_fn` will create a new graph every time, and that can trigger tf.function retracing warning.

Here is [the tensorflow document](https://tensorflow.google.cn/guide/function#tracing) to support it.

Briefly, for better efficiency, it's better to use:
```python
@tf.function
def inner():
    pass

def outer():
    inner()  
```
than:
```python
def outer():
    @tf.function
    def inner():
        pass
    inner()
```

Looking forward to your reply. Btw, I am glad to create a PR to fix it if you are too busy.

**Comment by cosmoquester** [comment]
aha... yes, you are right. thanks

**Comment by cosmoquester** [comment]
I corrected this, thank you again!
